### ISSUE TITLE
Uanble to Compare

### ISSUE THREAD

**Issue by karneaud** [percosys/git-controlhub#2]
Trying to compare files in git give me this error

> git --no-page diff .....
> Cannot read property 'push' of undefined

Guess it is similar to https://github.com/jacogr/atom-git-control/issues/40

**Comment by percosys** [comment]
I added the patch mentioned in https://github.com/jacogr/atom-git-control/issues/40 but I am unable to reproduce it myself, can you please test and close.

**Comment by mikolaj-kow** [comment]
I've tested your patch and it solves the issue. Thanks

**Comment by percosys** [comment]
Thank you!
